## 【問題1】これまで利用してきたクラスの列挙
<br>
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。<br>
<br>
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。<br>

・Pandas：DataFrame<br>
・matplotlib：Pyplot<br>
・scikit-learn:LogisticRegression<br>

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。<br>

・Pandas：DataFrame.info()、DataFrame.describe()、DataFrame.head()、DataFrame.tail()、DataFrame.shape<br>
・matplotlib：Pyplot.plot()、Pyplot.title()、Pyplot.xlabel()、Pyplot.ylabel()、Pyplot.show()<br>
・scikit-learn:LogisticRegression.fit()、LogisticRegression.predict()、LogisticRegression.score()、StandardScaler.fit_transform()、StandardScaler.transform()<br>

## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。<br>
```
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ =
        self.var_ =
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        pass
        return X_scaled
```
<br>
以下のコードが実行できるようにしましょう。<br>
<br>

```
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)
```


In [4]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean()
        self.var_ = X.var
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        # pass
        X_scaled = X
        return X_scaled


import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))

X_std = scratch_scaler.transform(X)

print(X_std)

平均 : 2.46
分散 : <built-in method var of numpy.ndarray object at 0x000001C72E077E10>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


## 【問題4】 四則演算を行うクラスの作成
```
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
```

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。<br>
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。<br>
クラス名や説明文も適切に書き換えてください。<br>

In [27]:
class ExampleClass():
    """
    四則演算のためのクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        # int型以外は「Error!」と表示
        if type(value2) is int:
            self.value += value2
        else:
            print("Error!")
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        # int型以外は「Error!」と表示
        if type(value2) is int:
            self.value -= value2
        else:
            print("Error!")
    def mul(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        # int型以外は「Error!」と表示
        if type(value2) is int:
            self.value *= value2
        else:
            print("Error!")
    def div(self, value2):
        """
        受け取った引数をself.valueから割る
        """
        # int型以外は「Error!」と表示
        if type(value2) is int:
            self.value /= value2
        else:
            print("Error!")

        
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(3)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))


初期値5が設定されました
value : 5
value : 8
value : 5
value : 15
value : 5.0
