## 【問題1】train_test_split のスクラッチ
まずは、scikit-learnの train_test_split をスクラッチしてみます。以下の雛形をベースに関数を実装してください。<br>
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html<br>
なお、作成した関数がscikit-learnの train_test_split と同じ動作をするか必ず確認をしましょう。<br>

### 雛形
```
def scratch_train_test_split(X, y, train_size=0.8):
    """検証データを分割する。
    Parameters
    ----------
    X : ndarray
      訓練データ (n_samples, n_features)
    y : ndarray
      正解値 (n_samples,)
    train_size : float
      何割をtrainとするか指定 (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      訓練データ (n_samples, n_features)
    X_test : ndarray
      検証データ (n_samples, n_features)
    y_train : ndarray
      訓練データの正解値 (n_samples,)
    y_test : ndarray
      検証データの正解値 (n_samples,)
    """
    # ここにコードを書く
    pass
    return X_train, X_test, y_train, y_test
```


In [69]:
import numpy as np
from sklearn.model_selection import train_test_split


def scratch_train_test_split(X, y, train_size=0.8):
    """検証データを分割する。
    Parameters
    ----------
    X : ndarray
      訓練データ (n_samples, n_features)
    y : ndarray
      正解値 (n_samples,)
    train_size : float
      何割をtrainとするか指定 (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      訓練データ (n_samples, n_features)
    X_test : ndarray
      検証データ (n_samples, n_features)
    y_train : ndarray
      訓練データの正解値 (n_samples,)
    y_test : ndarray
      検証データの正解値 (n_samples,)
    """
    # 戻り値計算
    X_train, X_test = np.split(X, [int(X.shape[0]*train_size)])
    y_train, y_test = np.split(y, [int(y.shape[0]*train_size)])

    return X_train, X_test, y_train, y_test

X = np.arange(12).reshape((4, 3))
y = np.arange(12).reshape((4, 3))

s_X_train, s_X_test, s_y_train, s_y_test = scratch_train_test_split(X, y, train_size=0.8)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=False)

print(s_X_train)
print(s_X_test)
print(s_y_train)
print(s_y_test)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]]


## 【問題2】 分類問題を解くコードの作成
### 分類問題
分類は3種類の手法をscikit-learnを使って実装します。<br>
　・ロジスティック回帰<br>
　・SVM<br>
　・決定木<br>
<br>
3種類のデータセットを用いて動作を確認します。<br>
　・1つ目は事前学習期間同様のirisデータセットです。<br>
　　2値分類としたいため、以下の2つの目的変数のみ利用します。特徴量は4種類すべて使います。<br>
　　「virgicolor」「virginica」<br>
　・シンプルデータセット1<br>
　・シンプルデータセット2<br>
上記3種類の手法で3種類のデータセットを学習・推定するコードを作成してください。<br>

```
# シンプルデータセット1 作成コード
import numpy as np
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X = np.concatenate([f0, f1])
y = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])
```

```
# シンプルデータセット2 作成コード
X = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```


In [117]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

### irisデータセットの作成
# irisのデータセットを読み込む
data = load_iris()
# 読み込んだデータセットをdataframeへ置き換える
p_data_x = pd.DataFrame(data.data)
p_data_y = pd.DataFrame(data.target)
# dataframeを結合し、カラム名を設定する
df_default = pd.concat([p_data_x, p_data_y],axis=1)
df_default = df_default.set_axis(["sepal_length","sepal_width","petal_length","petal_width","Species"], axis="columns")
# 今回使用しないカラムと行を削除
df_d_index = df_default.index[p_data_y[0] == 0]
df = df_default.drop(df_d_index)
# indexを振りなおす
df = df.reset_index(drop="True")
# 元のデータフレームから特徴量（説明変数）のみ、正解（目的変数）のみ、となるようにデータフレームを作成し、ndarrayに変換
X_iris = df.drop("Species", axis=1).values
y_iris = df.drop(["sepal_length","sepal_width","petal_length","petal_width"], axis=1).values

### シンプルデータセット1の作成
# シンプルデータセット1 作成コード
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X_smp1 = np.concatenate([f0, f1])
y_smp1 = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

### シンプルデータセット2の作成
# シンプルデータセット2 作成コード
X_smp2 = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y_smp2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
# print(X, y)

# train_test_splitにX、yを代入（デフォルト(指定なし)で訓練75%、検証25%となる）
X_iris_train, X_iris_test, y_iris_train, y_iris_test = scratch_train_test_split(X_iris, y_iris)
X_smp1_train, X_smp1_test, y_smp1_train, y_smp1_test = scratch_train_test_split(X_smp1, y_smp1)
X_smp2_train, X_smp2_test, y_smp2_train, y_smp2_test = scratch_train_test_split(X_smp2, y_smp2)

# またしても・・・警告回避
y_iris_train = y_iris_train.reshape(80,)
y_iris_test = y_iris_test.reshape(20,)

# インスタンス化
scaler_iris = StandardScaler()
scaler_smp1 = StandardScaler()
scaler_smp2 = StandardScaler()

# 訓練用のデータのみを.fitで標準化
scaler_iris.fit(X_iris_train)
scaler_smp1.fit(X_smp1_train)
scaler_smp2.fit(X_smp2_train)

# 訓練用、検証用双方のデータにtransformで標準化
tr_X_iris_train = scaler_iris.transform(X_iris_train)
tr_X_smp1_train = scaler_smp1.transform(X_smp1_train)
tr_X_smp2_train = scaler_smp2.transform(X_smp2_train)
tr_X_iris_test = scaler_iris.transform(X_iris_test)
tr_X_smp1_test = scaler_smp1.transform(X_smp1_test)
tr_X_smp2_test = scaler_smp2.transform(X_smp2_test)


In [118]:
# ロジスティック回帰
print("========== ロジスティック回帰 ==========")
# 学習
clf_iris = LogisticRegression(random_state=0).fit(tr_X_iris_train, y_iris_train)
clf_smp1 = LogisticRegression(random_state=0).fit(tr_X_smp1_train, y_smp1_train)
clf_smp2 = LogisticRegression(random_state=0).fit(tr_X_smp2_train, y_smp2_train)
# 推定
Y_iris_pred_LR = clf_iris.predict(tr_X_iris_test)
Y_smp1_pred_LR = clf_smp1.predict(tr_X_smp1_test)
Y_smp2_pred_LR = clf_smp2.predict(tr_X_smp2_test)


========== ロジスティック回帰 ==========


In [119]:
print("========== SVM ==========")
# 学習
clf_iris = make_pipeline(StandardScaler(), SVC(gamma='auto')).fit(X_iris_train,y_iris_train)
clf_smp1 = make_pipeline(StandardScaler(), SVC(gamma='auto')).fit(X_smp1_train,y_smp1_train)
clf_smp2 = make_pipeline(StandardScaler(), SVC(gamma='auto')).fit(X_smp2_train,y_smp2_train)
# 推定
Y_iris_pred_SVC = clf_iris.predict(tr_X_iris_test)
Y_smp1_pred_SVC = clf_smp1.predict(tr_X_smp1_test)
Y_smp2_pred_SVC = clf_smp2.predict(tr_X_smp2_test)


========== SVM ==========


In [120]:
print("========== 決定木 ==========")
# 学習
clf_iris = DecisionTreeClassifier(random_state=0).fit(X_iris_train,y_iris_train)
clf_smp1 = DecisionTreeClassifier(random_state=0).fit(X_smp1_train,y_smp1_train)
clf_smp2 = DecisionTreeClassifier(random_state=0).fit(X_smp2_train,y_smp2_train)
# 推定
Y_iris_pred_DTC = clf_iris.predict(tr_X_iris_test)
Y_smp1_pred_DTC = clf_smp1.predict(tr_X_smp1_test)
Y_smp2_pred_DTC = clf_smp2.predict(tr_X_smp2_test)


========== 決定木 ==========


## 【問題3】 回帰問題を解くコードの作成
線形回帰でHouse Pricesデータセットを学習・推定するコードを作成してください。<br>

### 線形回帰
線形回帰は勾配降下法を用いて計算する SGDRegressor クラスを利用してください。<br>
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html<br>

データセットは事前学習期間同様にHouse Pricesコンペティションのものを使います。<br>
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data<br>
train.csvをダウンロードし、目的変数としてSalePrice、説明変数として、GrLivAreaとYearBuiltを使います。<br>

In [122]:
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler


# ファイル名（パス）を指定する
csv_path = "E:/DiveIntoCode/source/train.csv" # 絶対パス
# 指数表示の禁止を設定する
np.set_printoptions(suppress=True)
# csvファイル読み込み
df_train = pd.read_csv(csv_path)
# Xに説明変数、yに目的変数となる列をそれぞれ抽出して代入
X = df_train[["GrLivArea","YearBuilt"]].values
y = df_train["SalePrice"].values

# train_test_splitにX、yを代入（デフォルト(指定なし)で訓練75%、検証25%となる）
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y)

# インスタンス化
scaler = StandardScaler()

# 訓練用のデータのみを.fitで標準化
scaler.fit(X_train)

# 訓練用、検証用双方のデータにtransformで標準化
tr_X_tarin = scaler.transform(X_train)
tr_X_test = scaler.transform(X_test)

# 線形回帰による学習
reg = make_pipeline(StandardScaler(),SGDRegressor(max_iter=1000, tol=1e-3)).fit(tr_X_tarin, y_train)

# 学習モデルによる推定
Y_pred = reg.predict(tr_X_test)

print(Y_pred)

[202928.38984856 415101.39127397 147732.22776908 142455.65180329
 190537.15527385 311229.01413394 223368.93740064 337121.09191004
 135556.4305198  106002.80384448 112687.1635931  124765.51797527
 299553.40888495 232470.27908956 500358.99028019  90530.02692416
 178433.55432674 103656.29083471 126494.42031698 215350.18607714
 227117.38763842 238330.98079213 181345.4131784  202316.09426943
 129583.58091373 180786.53400656 162752.95833212 209950.92067931
 251355.68265239 141992.44380224 181644.82856498 159582.78727629
 115360.68604125 234826.18204679 117280.97504923 222092.08141621
 141317.91765894 268003.17771631 130312.14357953 232110.40483511
 148736.11083762 231215.12627744 235227.73527421 221903.04223681
  66602.88473108 119763.11083113 120559.17482538 114239.38430494
 226540.88015278 199960.19131221  96560.98791123 151507.07615289
 113976.37712705 147739.27022967 191276.25946819 222097.35218048
 212299.78117595 130252.26050221 259325.13675178 115000.81178681
 237431.00726073 168911.3