【問題1】行列積を手計算する

A * B = [&nbsp;(-1 * 0)+(2 * 0)+(3 * 2)&emsp;(-1 * 2)+(2 * 2)+(3 * 9)&emsp;(-1 * 1)+(2 * -8)+(3 * -1)<br>
&emsp;&emsp;&emsp;&emsp;(4 * 0)+(-5 * 0)+(6 * 2)&emsp;(4 * 2)+(-5 * 2)+(6 * 9)&emsp;(4 * 1)+(-5 * -8)+(6 * -1)<br>
&emsp;&emsp;&emsp;&emsp;(7 * 0)+(8 * 0)+(-9 * 2)&emsp;(7 * 2)+(8 * 2)+(-9 * 9)&emsp;(7 * 1)+(8 * -8)+(-9 * -1)&nbsp;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;[&nbsp;&nbsp;6&nbsp;&nbsp;29&nbsp;&nbsp;-20<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;12&nbsp;&nbsp;52&nbsp;&nbsp;&nbsp;38<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-18&nbsp;-51&nbsp;-48&nbsp;]

【問題2】NumPyの関数による計算

In [7]:
import numpy as np


a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# numpy.matmul() を使用
print(np.matmul(a_ndarray, b_ndarray))

# numpy.dot() を使用
print(np.dot(a_ndarray, b_ndarray))

# @ を使用
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装

In [11]:
import numpy as np


a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

num = 0

for k in range(3):
    num += (a_ndarray[0,k] * b_ndarray[k,0])

print(num)

6


【問題4】行列積を行う関数の作成

In [34]:
import numpy as np


def matrix_product(a_ndarray, b_ndarray, ab_ndarray):
    num = 0
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[0]):
            for k in range(3):
                num += (a_ndarray[i,k] * b_ndarray[k,j])
            ab_ndarray[i,j] = num
            num = 0

    return ab_ndarray


a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.zeros((3, 3))
ab_ndarray = matrix_product(a_ndarray, b_ndarray, ab_ndarray)

print(ab_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


【問題5】計算が定義されない入力を判定する

In [50]:
import numpy as np


def matrix_product(a_ndarray, b_ndarray, ab_ndarray):
    num = 0
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[0]):
            for k in range(3):
                num += (a_ndarray[i,k] * b_ndarray[k,j])
            ab_ndarray[i,j] = num
            num = 0

    return ab_ndarray


#a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
#b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
a_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
ab_ndarray = np.zeros((a_ndarray.shape[1], b_ndarray.shape[0]))

if a_ndarray.shape[1] == b_ndarray.shape[0]:
    ab_ndarray = matrix_product(a_ndarray, b_ndarray, ab_ndarray)
else:
    print("a_ndarrayの列数「{}」とb_ndarrayの行数「{}」が一致していないため、計算することができません。".format(a_ndarray.shape[1],b_ndarray.shape[0]))



a_ndarrayの列数「3」とb_ndarrayの行数「2」が一致していないため、計算することができません。


【問題6】転置

In [55]:
import numpy as np


def matrix_product(a_ndarray, b_ndarray, ab_ndarray):
    num = 0
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[0]):
            for k in range(2): # ■■■■■ できれば変数にしたい ■■■■■
                num += (a_ndarray[i,k] * b_ndarray[k,j])
            ab_ndarray[i,j] = num
            num = 0

    return ab_ndarray


a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
ab_ndarray = np.zeros((a_ndarray.shape[1], b_ndarray.shape[0]))

if a_ndarray.shape[1] == b_ndarray.shape[0]:
    ab_ndarray = matrix_product(a_ndarray, b_ndarray, ab_ndarray)
else:
    print("a_ndarrayの列数「{}」とb_ndarrayの行数「{}」が一致していません。".format(a_ndarray.shape[1],b_ndarray.shape[0]))

    if a_ndarray.T.shape[1] == b_ndarray.shape[0]:
        print("a_ndarrayを転置して計算を行います。")
        a_ndarray_T = a_ndarray.T
        ab_ndarray = matrix_product(a_ndarray_T, b_ndarray, ab_ndarray)
    else:
        print("a_ndarrayを転置しても計算ができないため、処理を終了します。")

print(ab_ndarray)

a_ndarrayの列数「3」とb_ndarrayの行数「2」が一致していません。
a_ndarrayを転置して計算を行います。
[[ 33. -28.]
 [-48.  41.]
 [  9.  -6.]]
